FHG-5471 : Deployment Pipeline Sync (#23)
* feat: delete artifact after its used

* wip: test retrieving secret from azure keyvault

* wip: test retrieving secret from azure keyvault

* wip: test retrieving secret from azure keyvault

* wip: test only azure fetch

* wip: test only azure fetch

* wip: test only azure fetch

* wip: test only azure fetch

* wip: test deploying with az kv

* wip: test deploying with az kv

* wip: test mask

* wip: test mask

* wip: test mask

* wip: test mask

* wip: test mask

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: test az kv

* wip: revert

* wip: please

* wip: pretty please

* wip: test azure kv

* wip: test azure kv

* wip: test azure kv

* wip: test azure kv

* wip: optimise query

* wip: masking

* wip: masking

* wip: masking

* wip: masking

* wip: kv

* wip: kv

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: use kv in appsettings sub

* wip: test full deployment

* wip: what happens if you try and use keys and values not part of api

* wip: generic appsettings substitution

* wip: separate stages

* wip: test deploying 2 services

* wip: test deploying an api and a ui

* wip: test deploying an api and a ui

* wip: test deploying an api and a ui

* wip: test deploying an api and a ui

* wip: test deploying an api and a ui

* wip: test deploying an api and a ui

* wip: test deploying an api and a ui

* wip: test deploying an api and a ui

* wip: test deploying an api and a ui

* wip: test with full kv

* feat: deploy all services to dev

* refactor: fix prefix name for notif api

* refactor: provide name for az firewall rule

* refactor: correct some values

* refactor: multiple attempts to get IP address if times out or rate limits

* refactor: remove migration for idam maintenance ui

* chore: add clarifying comment

* refactor: nice names for build stages

* refactor: artefact->artifact

* fix: file??

---------

Co-authored-by: Aaron Yarborough <me@aaronjy.me>

diff --git a/.github/actions/get-runner-ip-address/action.yml b/.github/actions/get-runner-ip-address/action.yml
--- a/.github/actions/get-runner-ip-address/action.yml
+++ b/.github/actions/get-runner-ip-address/action.yml
@@ -9,10 +9,23 @@ runs:
   using: composite
 
   steps:
+    # Try and get the IP address of the Runner up-to MAX_TRIES times, waiting for an increasing delay for each failure
     - name: Get Workflow Runner IP
       id: get-ip
       shell: bash
       run: |
-        IP=$(curl -s https://api.ipify.org/)
-        echo "IP Address = $IP"
-        echo "ip_address=$IP" >> $GITHUB_OUTPUT
+        MAX_TRIES=8
+        DELAY=1
+        for TRY in $(seq $MAX_TRIES); do
+          IP=$(curl -s https://api.ipify.org/)
+          if [[ $IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "IP Address = $IP"
+            echo "ip_address=$IP" >> $GITHUB_OUTPUT
+            exit 0
+          fi
+          echo "Attempt $TRY / $MAX_TRIES to get IP address failed..."
+          sleep $DELAY
+          DELAY=$((DELAY + 1))
+        done
+        echo "Failed to get IP address after $MAX_TRIES attempts..."
+        exit 1
